console.log("Hello world");
var Nam = "jhon doe";
var age = 22;
var Admin = true;
console.log(Nam);
console.log(age);
console.log(Admin);
var firstName = "jhon";
var lastName = "doe";
var fullName = firstName + ' ' + lastName;
console.log(fullName);
var num = 10;
var start = "Hello";
var bool = true;
console.log(num);
console.log(start);
console.log(bool);
